[on-going] add aap ci test
securesign/artifact-signer-ansible pull request #119
Opened 2024-12-23 10:51 UTC by fghanmi

2025-01-02 21:01 UTC, fghanmi commented on .github/workflows/aap.yaml
> +# on:
To be uncommented once the PR is reviewed and build log is verified.

2025-01-06 14:07 UTC, tommyd450 commented
LGTM we can monitor it over the coming weeks to see if everything is up to scratch!

2025-01-07 10:27 UTC, SequeI commented
Thanks for the PR Firas! It looks in really solid shape 

@bkabrda I believe we could symlink a bunch of the unchanged files, or put some of the generic tasks like standing up the AWS infra into their own yml files and just `include_tasks` them to reduce code duplicity, WDYT? Although not sure if this is a big deal since this is just for testing.

2025-01-07 10:27 UTC, SequeI requested changes
Very good, just left a comment for Slavek to take a look at that might make sense for this PR

Thanks Firas!

2025-01-13 08:17 UTC, fghanmi commented on molecule/aap-setup/converge.yml
> +    - name: Error out if registry username is not set
@SequeI , I don't think we can use it, the when condition is based on different variable here: `aap_setup_prep_inv_secrets.all.registry_username`

2025-01-13 12:22 UTC, bkabrda commented on molecule/aap-collection-test/tasks/_parse_tf_results.yml
> +---
This file shouldn't be necessary as we're not using TF anymore.

2025-01-13 12:24 UTC, bkabrda commented
I definitely agree with @SequeI that we should reuse as much code as possible here by symlinking and/or reusing Ansible task files. Can you do that before I do a full review @fghanmi? Thanks!

2025-01-22 12:54 UTC, bkabrda commented on .github/workflows/aap.yaml
> +            molecule -v test --scenario-name aap-collection-test
I think this isn't using Molecule as it was meant to be used. This whole "setup" should be a part of the `prepare.yml` file inside the same Molecule scenario.

Furthermore, we shouldn't install the collection from AAP and run it locally, we want AAP to use it. Let me explain in more detail:

* Have 1 Molecule testing scenario, which creates 2 VMs
* In `prepare.yml`:
  * Install AAP on one of the VMs
  * Upload the collection to AAP
  * Create all AAP objects necessary to run the collection from AAP (something similar to https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/developing_ansible_automation_content/publishing-playbook-collection-aap#create-aap-job_publishing-playbook-collection-aap-intro)
* In `converge.yml`:
  * Trigger the AAP job and poll until it finishes
* In `verify.yml`:
  * Verify that TAS was installed correctly (e.g. use the verify from the `default` Molecule scenario)

Does that make sense? The important point here is that we need to test not only uploading the collection to AAP, but we need to ensure that it executes correctly *from AAP*.

2025-02-03 10:02 UTC, bkabrda commented on molecule/aap-test/verify.yml
> +  tasks:
Most of this file seems to be C&P from https://github.com/securesign/artifact-signer-ansible/blob/main/molecule/default/verify.yml - can we pull the shared tasks out to a common shared file?

2025-02-05 09:15 UTC, bkabrda commented on molecule/aap-test/molecule.yml
> +    image_id: ami-0cd93da2da7f10cab
Let's also use `ami-0dac29b55bd7c33aa` throughout this PR please (RHEL 9.4, upgraded for the whole collection in https://github.com/securesign/artifact-signer-ansible/pull/139/files)

2025-02-10 16:54 UTC, SequeI approved these changes
/lgtm left some very small comments, but this is essentially finished from what I have seen so far. Thanks a lot for dividing up the common tasks in their own files and editing the existing scenarios with them! Thanks Firas, this was especially frustrating to work on for sure

2025-02-10 16:54 UTC, SequeI commented on molecule/aap-test/converge.yml
> +        sed -f ../../vm-testing/dev-images.sed  -i ../../roles/tas_single_node/defaults/main.yml
I believe you could get rid of this task and reference Tomas' image mirroring PR where he adds the `podman.yml` as a `vars_files` and symlink the `podman.yml` in this scenarios `vars` folder [Like this](https://github.com/securesign/artifact-signer-ansible/pull/89/files#diff-bc4d0c4551c2773138cb727ed62a97e7e37f37731b8f6a2c8fe715ae136fdfb6R7) and [this](https://github.com/securesign/artifact-signer-ansible/pull/89/files#diff-521f50ba7612c8c6b66607e8d5a15c1890b8bc01bdab29beb55f814f54edf1f1). lmk what you think, might be better to reuse what is used in other scenarios currently

2025-02-10 16:54 UTC, SequeI commented on molecule/aap-test/converge.yml
> +                    enabled: false
This config is false by default so not sure it is needed here

2025-02-10 16:54 UTC, SequeI commented on molecule/aap-test/create.yml
> +          'identity_file': "{{ molecule_yml.platforms[0].aws_key_name }}",
Might be worthwhile creating a separate AAP-KEY keypair on AWS just to differentiate between the regular scenario CI runs and this scenario since it's a special midnight workflow. You can just put is in as an env var the same way it is shown in the [README](https://github.com/securesign/artifact-signer-ansible/blob/main/molecule/README.md)

2025-02-12 09:34 UTC, fghanmi commented on molecule/aap-test/create.yml
> +          'identity_file': "{{ molecule_yml.platforms[0].aws_key_name }}",
@SequeI Are there any specific gains or reasons for creating a separate AAP-KEY keypair for this ? Just wondering if it provides any concrete benefits beyond differentiation

2025-02-12 10:18 UTC, SequeI commented on molecule/aap-test/create.yml
> +          'identity_file': "{{ molecule_yml.platforms[0].aws_key_name }}",
@fghanmi Purely differentiation, esp as our collection grows mature and more complex in it's testing suite, might just make things easier in the future. No big deal though, up to you if you think it's worth it

2025-02-12 21:46 UTC, SequeI approved these changes
/lgtm Great, thanks Firas! 💯

2025-02-17 12:07 UTC, bkabrda approved these changes
Great job on this Firas, this is massive (and massively great and useful!)

2025-02-17 12:47 UTC, merged